# Generated by Django 3.2.20 on 2023-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('uf', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=40)),
                ('logradouro', models.CharField(max_length=70)),
                ('complemento', models.CharField(max_length=70)),
            ],
        ),
    ]
